service: cart-service

frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-optimize

useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  profile: aws-training
  stage: dev
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_NAME: ${env:DB_NAME}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          cors: true
          method: ANY
          path: /
      - http:
          cors: true
          method: ANY
          path: '{proxy+}'
